<?php

namespace AppBundle\Repository;

/**
 * AdValoremRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdValoremRepository extends \Doctrine\ORM\EntityRepository
{
}
