<?php

namespace AppBundle\Repository;

/**
 * AvisSocieteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvisSocieteRepository extends \Doctrine\ORM\EntityRepository
{
}
