<?php

namespace AppBundle\Repository;

/**
 * CalculDevisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalculDevisRepository extends \Doctrine\ORM\EntityRepository
{
}
