<?php

namespace AppBundle\Repository;

/**
 * CartonsFormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartonsFormRepository extends \Doctrine\ORM\EntityRepository
{
}
