<?php

namespace AppBundle\Repository;

/**
 * CpVilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CpVilleRepository extends \Doctrine\ORM\EntityRepository
{

}
