<?php

namespace AppBundle\Repository;
use DateTime;

/**
 * DemandeDevisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeDevisRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllDemandeDevis(){

        $now = new DateTime;
        $now->modify('-12 month');


        return $this->createQueryBuilder('db')
            ->where('db.CreatedDate >= :dateStart')
            ->setParameters([
                'dateStart' => $now,
            ])
            ->getQuery()
            ->execute()
            ;
    }

    public function getDevisByUuid($uuid) {
        return $this->createQueryBuilder('db')
            ->where('db.uuid = :uuid')
            ->setParameters([
               'uuid' => $uuid,
            ])
            ->getQuery()
            ->execute()
            ;
    }
}
