<?php

namespace AppBundle\Repository;

/**
 * DemandeDevisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeDevisRepository extends \Doctrine\ORM\EntityRepository
{
}
