<?php

namespace AppBundle\Repository;

/**
 * DevisEnvoyeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DevisEnvoyeRepository extends \Doctrine\ORM\EntityRepository
{
}
