<?php

namespace AppBundle\Repository;

/**
 * DevisConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DevisConfigRepository extends \Doctrine\ORM\EntityRepository
{
}
