<?php

namespace AppBundle\Repository;

/**
 * DistancematrixRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistancematrixRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $cpfrom
     * @param $cpto
     * @return mixed
     */
    public function getDistanceFromTo($cpfrom, $cpto) {
        return $this->createQueryBuilder('db')
            ->where('db.cpFrom = :cpfrom')
            ->andWhere('db.cpTo = :cpto')
            ->setParameters([
                'cpfrom' => $cpfrom,
                'cpto'   => $cpto
            ])
            ->getQuery()
            ->execute()
            ;
    }
}
