<?php

namespace AppBundle\Repository;

/**
 * DocPDFRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocPDFRepository extends \Doctrine\ORM\EntityRepository
{
}
