<?php

namespace AppBundle\Repository;

/**
 * DocPDFRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocPDFRepository extends \Doctrine\ORM\EntityRepository
{
    function findByDevisId($devis_id){

        $qb = $this->createQueryBuilder('a');


        return $qb
                ->select('a')
                ->leftJoin('a.id_devis', 'c')
                ->addSelect('c')
                ->add('where', $qb->expr()->in('c', ':c') )
            ->setParameter('c', $devis_id)
            ->orderBy('a.CreatedDate', 'DESC')
            ->getQuery()
            ->getResult();

    }
}
