<?php

namespace AppBundle\Repository;

/**
 * FranceSocieteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FranceSocieteRepository extends \Doctrine\ORM\EntityRepository
{
}
