<?php

namespace AppBundle\Repository;

/**
 * GardeMeubeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GardeMeubeRepository extends \Doctrine\ORM\EntityRepository
{
}
