<?php

namespace AppBundle\Repository;

/**
 * ImageBandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageBandeRepository extends \Doctrine\ORM\EntityRepository
{
}
