<?php

namespace AppBundle\Repository;

/**
 * PrestationCustomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrestationCustomRepository extends \Doctrine\ORM\EntityRepository
{
}
