<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * PrestationCustomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrestationCustomRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param User $user
     * @return array
     */
    public function findUserPrestations(User $user) {

        // Check if user have parent
        if(!is_null($user->getParent())) {
            $user = $user->getParent();
        }

        $query = $this->createQueryBuilder('a')
            ->select('a.prestation')
            ->where('a.user_id =:userid')
            ->groupBy('a.prestation')
            ->setParameters([
                'userid' => $user,
            ])
            ->getQuery()
            ->getResult();

        /** @var array $resultArray */
        $resultArray = [];
        foreach ($query as $prestation) {
            $resultArray[$prestation['prestation']] = $prestation['prestation'];
        }

        return $resultArray;
    }

    /**
     * @param User $userid
     * @param $typePrestation
     * @return array
     */
    public function findByCompetence(User $userid, $typePrestation){

        // Check if user have parent
        if(!is_null($userid->getParent())) {
            $userid = $userid->getParent();
        }

        $query = $this->createQueryBuilder('a')
            ->where('a.user_id =:userid')
            ->andWhere('a.prestation = :prestation')
            ->select('a')
            ->leftJoin('a.descriptions', 'c')
            ->addSelect('c')
            ->setParameters([
                'userid' => $userid,
                'prestation' => $typePrestation,
            ])
            ->getQuery()
            ->getResult();


        $resultArray = [];
        foreach ($query as $prestation) {
            $descriptions = [];
            foreach ($prestation->getDescriptions() as $description) {
                $descriptions[] = $description->getDescription();
            }
            $resultArray[$prestation->getChargepar()] = $descriptions;
        }

        return $resultArray;
    }
}
