<?php

namespace AppBundle\Repository;

/**
 * PrestationDescriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrestationDescriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
