<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;

/**
 * ReadyDemandeDevisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReadyDemandeDevisRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param User $user
     * @param mixed $uuid
     * @return array
     */
    public function getReadedDemandeDevis(User $user, $uuid) {
        return $this->findBy([
            'idUser' => $user,
            'uuidDevis' => $uuid,
        ]);
    }
}
