<?php

namespace AppBundle\Repository;

/**
 * RIBRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RIBRepository extends \Doctrine\ORM\EntityRepository
{
}
