<?php

namespace AppBundle\Repository;

/**
 * SousTraitanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousTraitanceRepository extends \Doctrine\ORM\EntityRepository
{
}
