<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * TelephoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TelephoneRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param User $user
     * @return array
     */
    public function findUserAllTelephone(User $user){
        // Check if user have parent
       if(!is_null($user->getParent())) {
            $user = $user->getParent();
        }

        $query = $this->createQueryBuilder('a')
            ->where('a.user_id =:userid')
            ->setParameters([
                'userid' => $user,
            ])
            ->getQuery()
            ->getResult();

        /** @var array $resultArray */

        $resultArray = [];
        foreach ($query as $telephone) {
            $resultArray[$telephone->getType()][] = $telephone->getNumero();
        }

        return $resultArray;
    }
}
