<?php

namespace AppBundle\Repository;

/**
 * VisitetechniqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisiteTechniqueRepository extends \Doctrine\ORM\EntityRepository
{
}
