imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: '@AppBundle/yml/menu/topmenu.yml' }
    - { resource: '@AppBundle/yml/menu/top_sous_menu.yml' }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    cssFileName: pages.css
    jsFileName: pages.js
    admin: adminss

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    templating:
        engines: ['twig']

# Twig Configuration
twig:
    form_themes:
        - 'TetranzSelect2EntityBundle:Form:fields.html.twig'
        - 'form/fields.html.twig'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths: ["%kernel.project_dir%/webTwig/"]
    globals:
        cssFileName: '%cssFileName%'
        jsFileName: '%jsFileName%'
        topmenu: '%topmenu%'
        top_sous_menu: '%topmenu_sous_menu%'


# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        default_entity_manager: default



# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
    registration:
        form:
            type: AppBundle\Form\RegistrationType

sonata_block:
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]

sonata_admin:
    title: 'Admin'
    search: false
    title_logo: favicon.ico
    assets:
        stylesheets:
          - bundles/sonatacore/vendor/bootstrap/dist/css/bootstrap.min.css
          - https://use.fontawesome.com/releases/v5.3.1/css/all.css
          - bundles/sonatacore/vendor/ionicons/css/ionicons.min.css
          - bundles/sonataadmin/vendor/admin-lte/dist/css/AdminLTE.min.css
          - bundles/sonataadmin/vendor/admin-lte/dist/css/skins/skin-black.css
          - bundles/sonataadmin/vendor/iCheck/skins/square/blue.css
          - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css
          - bundles/sonataadmin/vendor/jqueryui/themes/base/jquery-ui.css
          - bundles/sonatacore/vendor/select2/select2.css
          - bundles/sonatacore/vendor/select2-bootstrap-css/select2-bootstrap.min.css
          - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css
          - bundles/sonataadmin/css/styles.css
          - bundles/sonataadmin/css/layout.css
          - bundles/sonataadmin/css/tree.css
          - bundles/sonataadmin/css/colors.css
    dashboard:
        groups:
            admin:
                label:              Admin
                label_catalogue:    SonataAdminBundle
                icon:               '<i class="fa fa-users"></i>'
                items:
                    - route:        sonata_admin_user
                      label:        Users
                      roles:        [ROLE_SUPER_ADMIN]

                    - route:        sonata_admin_seo
                      label:        'SEO'
                      roles:        [ROLE_SUPER_ADMIN]

            web:
                label: Web
                label_catalogue:    SonataAdminBundle
                items:
                   - route:        sonata_admin_article
                     label:        'Web'
                     roles:        [ROLE_ADMIN]

                   - route:        sonata_admin_bande
                     label:        'Bande'
                     roles:        [ROLE_ADMIN]

                   - route:        sonata_societe
                     label:        'Societe'
                     roles:        [ROLE_ADMIN]

                   - route:        sonata_admin_image_bande
                     label:        'Image Bande'
                     roles:        [ROLE_ADMIN]

                   - route:        sonata_admin_garde_meuble
                     label:        'Garde Meuble'
                     roles:        [ROLE_ADMIN]

                   - route:        sonata_admin_prestation
                     label:        'Prestation'
                     roles:        [ROLE_ADMIN]

                   - route:        sonata_admin_cp_ville
                     label:        'Cp Ville'
                     roles:        [ROLE_ADMIN]

                   - route:        sonata_admin_social
                     label:        'Social Buttons'
                     roles:        [ROLE_ADMIN]

                   - route:        sonata_admin_calculdevis
                     label:        'Calcul Devis'
                     roles:        [ROLE_ADMIN]

                   - route:        sonata_admin_demande_devis
                     label:        'Demande Devis'
                     roles:        [ROLE_ADMIN]

                   - route:        sonata_admin_contact
                     label:        'Contact'
                     roles:        [ROLE_ADMIN]

                   - route:        sonata_admin_carton
                     label:        'Carton'
                     roles:        [ROLE_ADMIN]

                   - route:        sonata_admin_carton_form
                     label:        'Carton Form'
                     roles:        [ROLE_ADMIN]

                   - route:        sonata_admin_france_societe
                     label:        'France Societe'
                     roles:        [ROLE_ADMIN]

                   - route:        sonata_admin_visiste_technique
                     label:        'Visiste Technique'
                     roles:        [ROLE_ADMIN]



