imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: '@AppBundle/yml/menu/topmenu.yml' }


# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    cssFileName: pages.css
    jsFileName: pages.js
    admin: espace

framework:
    #esi: ~
    translator: { fallbacks: ['fr'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    templating:
        engines: ['twig']

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths: ["%kernel.project_dir%/webTwig"]
    globals:
        cssFileName: '%cssFileName%'
        jsFileName: '%jsFileName%'
        topmenu: '%topmenu%'
    form_themes:
        - '@SonataCore/Form/datepicker.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        types:
          uuid:  Ramsey\Uuid\Doctrine\UuidType

      # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true


liip_imagine :
    resolvers :
        default :
            web_path : ~

    filter_sets :
        cache : ~

        # the name of the "filter set"
        my_thumb :

            # adjust the image quality to 75%
            quality : 75

            # list of transformations to apply (the "filters")
            filters :

                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail  : { size : [120, 90], mode : outbound }

                # create a 2px black border: center the thumbnail on a black background
                # 4px larger to create a 2px border around the final image
                background : { size : [124, 94], position : center, color : '#000000' }

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User
    group:
        group_class: AppBundle\Entity\Group
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
    registration:
        form:
            type: AppBundle\Form\RegistrationType

sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.block.service.text:

sonata_admin:
    security:
        handler: sonata.admin.security.handler.role

    title: 'Espace Déménageur'
    search: false
    templates:
        layout:      'admin/standard_layout.html.twig'
        list_block:  'admin/block_admin_list.html.twig'
        dashboard:   'admin/dashboard/base.html.twig'
        list:        'admin/dashboard/list.html.twig'
        button_create:  'admin/dashboard/create_button.html.twig'
        knp_menu_template: 'admin/dashboard/menu/sonata_menu.html.twig'
    assets:
        stylesheets:
          - https://use.fontawesome.com/releases/v5.6.1/css/all.css
          - https://fonts.googleapis.com/css?family=Titillium+Web:400
          - bundles/sonatacore/vendor/bootstrap/dist/css/bootstrap.min.css
          - bundles/sonatacore/vendor/ionicons/css/ionicons.min.css
          - bundles/sonataadmin/vendor/admin-lte/dist/css/AdminLTE.min.css
          - bundles/sonataadmin/vendor/admin-lte/dist/css/skins/skin-black.css
          - bundles/sonataadmin/vendor/iCheck/skins/square/blue.css

          - bundles/sonatacore/vendor/select2/select2.css
          - bundles/sonatacore/vendor/select2-bootstrap-css/select2-bootstrap.min.css
          - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css
          - bundles/sonataadmin/css/styles.css
          - bundles/sonataadmin/css/layout.css
          - bundles/sonataadmin/css/tree.css
          - bundles/sonataadmin/css/colors.css
          - /css/admin/dashboard/custom.css?vkl
          - /css/admin/datepicker.css

        javascripts:

          # The default javascript list:
          - 'bundles/sonatacore/vendor/jquery/dist/jquery.min.js'
          - 'bundles/sonataadmin/vendor/jquery.scrollTo/jquery.scrollTo.min.js'
          - 'bundles/sonataadmin/vendor/jqueryui/ui/minified/i18n/jquery-ui-i18n.min.js'
          - 'bundles/sonatacore/vendor/moment/min/moment.min.js'
          - 'bundles/sonatacore/vendor/bootstrap/dist/js/bootstrap.min.js'
          - 'bundles/sonataadmin/vendor/jquery-form/jquery.form.js'
          - 'bundles/sonataadmin/jquery/jquery.confirmExit.js'
          - 'bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/js/bootstrap-editable.min.js'
          - 'bundles/sonatacore/vendor/select2/select2.min.js'
          - 'bundles/sonataadmin/vendor/admin-lte/dist/js/app.min.js'
          - 'bundles/sonataadmin/vendor/iCheck/icheck.min.js'
          - 'bundles/sonataadmin/vendor/slimScroll/jquery.slimscroll.min.js'
          - 'bundles/sonataadmin/vendor/waypoints/lib/jquery.waypoints.min.js'
          - 'bundles/sonataadmin/vendor/waypoints/lib/shortcuts/sticky.min.js'
          - 'bundles/sonataadmin/vendor/readmore-js/readmore.min.js'
          - 'bundles/sonataadmin/vendor/masonry/dist/masonry.pkgd.min.js'
          - 'bundles/sonataadmin/Admin.js'
          - 'bundles/sonataadmin/treeview.js'
          - 'bundles/sonataadmin/sidebar.js'

        extra_javascripts:
          -  https://code.jquery.com/ui/1.12.1/jquery-ui.js
          - /js/datepicker-fr.js
          - /js/list-table-striped.js

    dashboard:
        blocks:

            -
                position: left
                type: sonata.admin.block.admin_list
                settings:
                    groups:
                       - espace

            -
                position: right
                type: sonata.admin.block.admin_list
                settings:
                  groups:
                    - mon_compte

       #     -
       #         position: right
       #         type: sonata.block.service.text
       #         settings:
       #             content: >
       #                 <h2>Welcome to the Sonata Admin</h2>
       #                 <p>This is a <code>sonata.block.service.text</code> from the Block
       #                 Bundle, you can create and add new block in these area by configuring
       #                 the <code>sonata_admin</code> section.</p> <br/> For instance, here
       #                 a RSS feed parser (<code>sonata.block.service.rss</code>):


        groups:

            admin:
                keep_open:          true
                label:              Admin
                label_catalogue:    SonataAdminBundle
                icon:               '<i class="fa fa-users"></i>'
                items:
                    - admin.users
                    - admin.group

            espace:
                keep_open:          true
                label:              Espace
                icon:               '<i class="fas fa-desktop"></i>'
                items:
                    - admin.demandedevis
                    - admin.mesdevis
                    - admin.devisenvoye
                    - admin.soustraitance



            parametres:
                keep_open:          true
                label:              Paramètres
                icon:               '<i class="fas fa-cogs"></i>'
                items:
                   - route:        sonata_admin_ma_societe
                     label:        Ma Societe
                     roles:        [ROLE_SOCIETE]

                   - route:        sonata_admin_devis_conf
                     label:        devis.tarification
                     roles:        [ROLE_SOCIETE]

            mon_compte:
                keep_open:          true
                label:              Mon Compte
                icon:               '<i class="fas fa-money-check-alt"></i>'
                items:
                    - route:        sonata_admin_user
                      label:        Crédits / Paiment
                      roles:        [ROLE_SOCIETE]

                    - admin.users.connection
                    - admin.mesfactures


