imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: '@AppBundle/yml/menu/topmenu.yml' }
    - { resource: sonata/sonata_block.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    cssFileName: pages.css
    jsFileName: pages.js
    admin: espace

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    templating:
        engines: ['twig']

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths: ["%kernel.project_dir%/webTwig"]
    globals:
        cssFileName: '%cssFileName%'
        jsFileName: '%jsFileName%'
        topmenu: '%topmenu%'
    form_themes:
        - '@SonataCore/Form/datepicker.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        types:
          uuid:  Ramsey\Uuid\Doctrine\UuidType

      # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true



# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
    registration:
        form:
            type: AppBundle\Form\RegistrationType

sonata_block:
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]

sonata_admin:
    title: 'Espace Déménageur'
    search: false
    templates:
        layout: 'admin/standard_layout.html.twig'
    assets:
        stylesheets:
          - https://use.fontawesome.com/releases/v5.6.1/css/all.css
          - https://fonts.googleapis.com/css?family=Titillium+Web:400
          - bundles/sonatacore/vendor/bootstrap/dist/css/bootstrap.min.css
          - bundles/sonatacore/vendor/ionicons/css/ionicons.min.css
          - bundles/sonataadmin/vendor/admin-lte/dist/css/AdminLTE.min.css
          - bundles/sonataadmin/vendor/admin-lte/dist/css/skins/skin-black.css
          - bundles/sonataadmin/vendor/iCheck/skins/square/blue.css

          - bundles/sonatacore/vendor/select2/select2.css
          - bundles/sonatacore/vendor/select2-bootstrap-css/select2-bootstrap.min.css
          - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css
          - bundles/sonataadmin/css/styles.css
          - bundles/sonataadmin/css/layout.css
          - bundles/sonataadmin/css/tree.css
          - bundles/sonataadmin/css/colors.css
          - /css/admin/dashboard/custom.css?vkl
          - /css/admin/datepicker.css

        javascripts:

          # The default javascript list:
          - 'bundles/sonatacore/vendor/jquery/dist/jquery.min.js'
          - 'bundles/sonataadmin/vendor/jquery.scrollTo/jquery.scrollTo.min.js'
          - 'bundles/sonataadmin/vendor/jqueryui/ui/minified/i18n/jquery-ui-i18n.min.js'
          - 'bundles/sonatacore/vendor/moment/min/moment.min.js'
          - 'bundles/sonatacore/vendor/bootstrap/dist/js/bootstrap.min.js'
          - 'bundles/sonataadmin/vendor/jquery-form/jquery.form.js'
          - 'bundles/sonataadmin/jquery/jquery.confirmExit.js'
          - 'bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/js/bootstrap-editable.min.js'
          - 'bundles/sonatacore/vendor/select2/select2.min.js'
          - 'bundles/sonataadmin/vendor/admin-lte/dist/js/app.min.js'
          - 'bundles/sonataadmin/vendor/iCheck/icheck.min.js'
          - 'bundles/sonataadmin/vendor/slimScroll/jquery.slimscroll.min.js'
          - 'bundles/sonataadmin/vendor/waypoints/lib/jquery.waypoints.min.js'
          - 'bundles/sonataadmin/vendor/waypoints/lib/shortcuts/sticky.min.js'
          - 'bundles/sonataadmin/vendor/readmore-js/readmore.min.js'
          - 'bundles/sonataadmin/vendor/masonry/dist/masonry.pkgd.min.js'
          - 'bundles/sonataadmin/Admin.js'
          - 'bundles/sonataadmin/treeview.js'
          - 'bundles/sonataadmin/sidebar.js'

        extra_javascripts:
          -  https://code.jquery.com/ui/1.12.1/jquery-ui.js
          - /js/datepicker-fr.js

    dashboard:
        blocks:
            -
                position: left
                type: sonata.admin.block.admin_list
        groups:
            admin:
                keep_open:          true
                label:              Admin
                label_catalogue:    SonataAdminBundle
                icon:               '<i class="fa fa-users"></i>'
                items:
                    - route:        sonata_admin_user
                      label:        Users
                      roles:        [ROLE_SUPER_ADMIN]

            espace:
                keep_open:          true
                label:              Espace
                icon:               '<i class="fas fa-desktop"></i>'
                items:
                    - route:        sonata_admin_demande_devis
                      label:        Devis
                      roles:        [ROLE_CLIENT]

                    - route:        sonata_admin_devis_envoye
                      label:        Ajouter / Envoyer
                      roles:        [ROLE_CLIENT]

            parametres:
                keep_open:          true
                label:              Paramètres
                icon:               '<i class="fas fa-cogs"></i>'
                items:
                   - route:        sonata_admin_user
                     label:        Ma Societe
                     roles:        [ROLE_CLIENT]

                   - route:        sonata_admin_user
                     label:        Devis / Tarification
                     roles:        [ROLE_CLIENT]

            payement:
                keep_open:          true
                label:              Mon Compte
                icon:               '<i class="fas fa-money-check-alt"></i>'
                items:
                    - route:        sonata_admin_user
                      label:        Crédits / Paiment
                      roles:        [ROLE_CLIENT]

                    - route:        sonata_admin_user
                      label:        Facture
                      roles:        [ROLE_CLIENT]

