app:
    resource: '@AppBundle/Controller/'
    type: annotation

admin_area:
    resource: '@AppBundle/Resources/config/routing/sonata_admin.xml'
    prefix: %admin%

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /%admin%

sonata_societe:
    path: /%admin%/app/societe/list

sonata_admin_user:
    path: /%admin%/app/user/list

sonata_admin_demande_devis:
    path: /%admin%/app/demandedevis/list

sonata_admin_devis_envoye:
    path:  /%admin%/app/devisenvoye/list

sonata_admin:
    path: /%admin%/


fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile