# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html

## Ruben SEARCH for this
# dump($this->getBaseRole($admin));
# RoleSecurityHandler isGranted(AdminInterface $admin, $attributes, $object = null)
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_GROUP_SOCIETE:
          - ROLE_CLIENT
          - ROLE_ADMIN_MESDEVIS_LIST
          - ROLE_ADMIN_MESDEVIS_VIEW
          - ROLE_ADMIN_MESDEVIS_CREATE
          - ROLE_ADMIN_MESDEVIS_EDIT
          - ROLE_ADMIN_MESDEVIS_ROLE_ALL_DEVIS_ENVOYE_READER
          - ROLE_ADMIN_DEVISENVOYE_ROLE_ALL_DEVIS_ENVOYE_READER
          - ROLE_ADMIN_DEVISENVOYE_VIEW
          - ROLE_ADMIN_DEVISENVOYE_LIST
          - ROLE_ADMIN_DEVISENVOYE_EDIT

        ROLE_SOCIETE:
          - ROLE_CLIENT
          - ROLE_ADMIN_GROUP_ALL
          - ROLE_ADMIN_PRESTATION_ALL
          - ROLE_ADMIN_TELEPHONE_ALL
          - ROLE_ADMIN_DEMANDEDEVIS_LIST
          - ROLE_ADMIN_DEMANDEDEVIS_VIEW
          - ROLE_ADMIN_DEVISENVOYE_LIST
          - ROLE_ADMIN_DEVISENVOYE_VIEW
          - ROLE_ADMIN_DEVISENVOYE_EDIT
          - ROLE_ADMIN_DEVISENVOYE_DELETE
          - ROLE_ADMIN_MESDEVIS_ALL
          - ROLE_ADMIN_USERS_CONNECTION_LIST
          - ROLE_ADMIN_SOUSTRAITANCE_LIST
          - ROLE_ADMIN_SOUSTRAITANCE_VIEW
          - ROLE_ADMIN_MESFACTURES_LIST
          - ROLE_ADMIN_MESFACTURES_VIEW

        ROLE_ADMIN:  ROLE_ADMIN
        ROLE_ALL_DEVIS_ENVOYE_READER:
          - ROLE_ALL_DEVIS_ENVOYE_READER

        ROLE_SUPER_ADMIN: [ROLE_CLIENT, ROLE_CLIENT_GROUP, ROLE_ADMIN, ROLE_ALL_DEVIS_ENVOYE_READER ,ROLE_ALLOWED_TO_SWITCH]

    access_decision_manager:
        strategy: unanimous


    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
            logout: true
            anonymous: true
            access_denied_handler: AppBundle\Security\AccessDeniedHandler
            switch_user:
              provider:   fos_userbundle
           # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%admin%/, roles: ROLE_CLIENT }

