# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    admin.users:
        class: AppBundle\Admin\UsersAdmin
        arguments:
           - ~
           - AppBundle\Entity\User
           - ~
        tags:
            - { name: sonata.admin, manager_type: orm, label: Users, group : 'Admin' }
        public: true


    admin.societe:
        class: AppBundle\Admin\SocieteAdmin
        arguments:
           - ~
           - AppBundle\Entity\Societe
           - ~
        tags:
            - { name: sonata.admin, manager_type: orm, label: Societe, group : 'Admin' }
        public: true

    admin.bande:
        class: AppBundle\Admin\BandeAdmin
        arguments:
           - ~
           - AppBundle\Entity\Bande
           - ~
        tags:
            - { name: sonata.admin, manager_type: orm, route: '/bande', label: Bande, group : 'Admin' }
        public: true

    admin.article:
        class: AppBundle\Admin\ArticlesAdmin
        arguments:
           - ~
           - AppBundle\Entity\Articles
           - ~
        tags:
            - { name: sonata.admin, manager_type: orm, route: '/articles', label: Article, group : 'Web' }
        public: true

    admin.imagebande:
        class: AppBundle\Admin\ImageBandeAdmin
        arguments:
           - ~
           - AppBundle\Entity\ImageBande
           - ~
        tags:
            - { name: sonata.admin, manager_type: orm, route: '/imagebande', label: 'Image Bande', group : 'Web' }
        calls:
            - [ setTemplate, [ edit, "admin/imagebande_edit.html.twig"]]
        public: true

    admin.prestation:
        class: AppBundle\Admin\PrestationAdmin
        arguments:
           - ~
           - AppBundle\Entity\Prestation
           - ~
        tags:
            - { name: sonata.admin, manager_type: orm, route: '/prestation', label: 'Prestation', group : 'Web' }
        public: true

    admin.cpville:
        class: AppBundle\Admin\CpVilleAdmin
        arguments:
           - ~
           - AppBundle\Entity\CpVille
           - ~
        tags:
            - { name: sonata.admin, manager_type: orm, route: '/cpville', label: 'Cp Ville', group : 'Web' }
        public: true


    admin.social:
        class: AppBundle\Admin\SocialAdmin
        arguments:
           - ~
           - AppBundle\Entity\Social
           - ~
        tags:
            - { name: sonata.admin, manager_type: orm, route: '/social', label: 'Social Buttons', group : 'Web' }
        public: true


    admin.calcul_devis:
        class: AppBundle\Admin\CalculDevisAdmin
        arguments:
           - ~
           - AppBundle\Entity\CalculDevis
           - ~
        tags:
            - { name: sonata.admin, manager_type: orm, route: '/calculdevis', label: 'Calcul Devis', group : 'Web' }
        public: true


    admin.contact:
        class: AppBundle\Admin\ContactAdmin
        arguments:
           - ~
           - AppBundle\Entity\Contact
           - ~
        tags:
            - { name: sonata.admin, manager_type: orm, route: '/contact', label: 'Contact', group : 'Web' }
        public: true

    # add more services, or override services that need manual wiring
    # AppBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value'
