<?php

namespace AppBundle\Form\Type;

use AppBundle\Entity\Telephone;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TelephoneType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('tel')
            ->add('fax',TextType::class,array(
                'required' => false,
                'empty_data' => ''
            ))
        ;
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
          array(
              'data_class' => Telephone::class,
          )
        );
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }
}