<?php


namespace AppBundle\Form;

use AppBundle\Entity\AdValorem;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class AdValoremForm
 * @package AppBundle\Form
 */
class AdValoremForm extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('description', TextType::class, [
                'label' => 'Description',
                'attr' => [
                    'class' => 'form-control description',
                    'divclass' => 'col-md-6'
                ],
            ])
            ->add('price', TextType::class, [
                'label' => 'Prix',
                'attr' => [
                    'class' => 'form-control prix',
                    'divclass' => 'col-md-6'
                ],
            ])
        ;

        /*

        var advalorem = [];
$('div[id*=advalorem_]').each(function(){

        description = $(this).find("input.description").val();
	prix        = $(this).find("input.prix").val();

	if(description.length>0 && prix.length>0)
	{
		advalorem.push({
  			'description': $(this).find("input.description").val(),
			'prix'       : $(this).find("input.prix").val()
        	});
	}
})
console.log(JSON.stringify(advalorem));


         */


        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => AdValorem::class
        ]);
    }
}