<?php
/**
 * Created by PhpStorm.
 * User: rpetrosjan
 * Date: 14/01/2019
 * Time: 01:30
 */

namespace AppBundle\Admin;


use AppBundle\Entity\DemandeDevis;
use AppBundle\Entity\DevisConfig;
use AppBundle\Entity\DevisEnvoye;
use AppBundle\Entity\SendDevis;
use AppBundle\Form\EstimationPrixForm;
use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Show\ShowMapper;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

/**
 * Class DevisEnvoyeAdmin
 * @package AppBundle\Admin
 */
class DevisEnvoyeAdmin extends AbstractAdmin
{

    private $object;

    // Creating Sort By DateTime ASC
    protected $datagridValues = [
        '_page' => 1,
        '_sort_order' => 'DESC',
        '_sort_by' => 'CreatedDate',
    ];

    public function configure() {

        /// $this->setTemplate('list','@AppBundle/Admin/ContactList.html.twig');
        $this->setTemplate('edit','admin/calculDevisAdminEdit.html.twig');
        $this->setTemplate('show','admin/calculDevisAdminShow.html.twig');
    }

    /**
     * We check if user is Owner of the devis?
     *
     * @param string $action
     * @param null $object
     */
    public function checkAccess($action, $object = null)
    {

        if(strcmp('list', $action) !=0 ) {

            /** @var int  $currentUSerId */
            $currentUSerId = $this->getConfigurationPool()->getContainer()->get('security.token_storage')->getToken()->getUser()->getId();
    
            /** @var int $devisOwnerId */
            $devisOwnerId = $object->getUserId()->getId();

            if(false === $this->isGranted('ROLE_ALL_DEVIS_ENVOYE_READER') && $currentUSerId != $devisOwnerId) {
                throw new AccessDeniedException(sprintf('Access Denied to the action'));
            }
        }
        parent::checkAccess($action, $object); // TODO: Change the autogenerated stub

    }


    // Filtering list result for calcul devis en ligne
    public function createQuery($context = 'list')
    {
        $container = $this->getConfigurationPool()->getContainer();
        $userEntity = $container->get('security.token_storage')->getToken()->getUser();

        $query = parent::createQuery($context);
        $query->where(
            $query->getRootAliases()[0].'.user_id = '.$userEntity->getId()
        );
        return $query;
    }

    public function getDashboardActions()
    {
        $actions = parent::getDashboardActions();
    }

    // We wel recreate getObject in par Defaut it serach with id getObject find
    public function getObject($id)
    {
        /** @var  $object DevisEnvoye */
        $object = $this->getModelManager()->findOneBy($this->getClass(), [
            'uuid' => $id
        ]);
        $this->object = $object;
        return $object;
    }

    // We call new function for generating URL sonata
    public function getUrlsafeIdentifier($entity)
    {
        return $this->getNormalizedIdentifier($entity);
    }

    // Here url make new paramters tu URL uuid
    public function getNormalizedIdentifier($entity)
    {
        // If id not exist it wille be create
        if(is_null($entity->getId()))
        {
            return parent::getNormalizedIdentifier($entity);
        }
        // If id exist wie show url with UUID paramter
        else{
            return $entity->getUuid();
        }
    }


    // Show Result in the Page
    protected function configureFormFields(FormMapper $formMapper) {


        $formMapper

            ->with('General', [
                    'class'       => 'col-md-6',
                    'attr' => [
                        'icon' => '<i class="fas fa-clipboard-list"></i>',
                    ],
                ]
            )
            ->add('nom')
            ->add('prenom')
            ->add('telephone')
            ->add('email')

            ->end()
            ->with('Info Date', [
                'class'       => 'col-md-6 title_devis',
                'attr' => [
                    'icon' => '<i class="fas fa-info"></i>',
                ]
            ])
            ->add('CreatedDate', 'sonata_type_date_picker', [
                'label' => 'Date de demande',
                'format'=>'dd/MM/yyyy',
                'required' => false,
                'attr' => [
                    'class' => 'datepicker'
                ]
            ])
            ->add('volume', TextType::class, [
                'label' => 'Volume',
            ])
            ->add('prestation', ChoiceType::class, [
                'label' => 'Prestation',
                'choices'  => array(
                    'Economique' => 'Economique',
                    'Standard' => 'Standard',
                    'Luxe' => 'Luxe'
                ),
            ])
            ->add('budget', TextType::class, [
                'label' => 'Budget prevu',
                'disabled' => true,
                'mapped' => false,
            ])
            ->end()

            ->with('Info Depart' ,[
                'class'       => 'col-md-6',
                'attr' => [
                    'icon' => '<i class="fas fa-map-signs"></i>',
                ]
            ])
            ->add('date1', TextType::class, [
                'attr' => [
                    'class' => 'datepicker'
                ]
            ])
            ->add('adresse1')
            ->add('cp1')
            ->add('ville1')
            ->add('etage1')
            ->add('ascenseur1',ChoiceType::class,[
                'empty_data'  => true,
                'choices'  => array(
                    'Oui' => 'Oui',
                    'No' => 'No',
                ),
            ])
            ->end()
            ->with('Info Arrivee' ,[
                'class'       => 'col-md-6',
                'attr' => [
                    'icon' => '<i class="fas fa-map-signs"></i>',
                ]
            ])
            ->add('date2')
            ->add('adresse2')
            ->add('cp2')
            ->add('ville2')
            ->add('etage2')
            ->add('ascenseur2', ChoiceType::class,[
                'empty_data'  => true,
                'choices'  => array(
                    'Oui' => 'Oui',
                    'No' => 'No',
                ),
            ])
            ->end()

        ;

    }

    protected function configureDatagridFilters(DatagridMapper $datagridMapper) {
        $datagridMapper
            ->add('CreatedDate')
            ->add('nom')
            ->add('prenom')
            ->add('cp1')
            ->add('cp2')
            ->add('date')
        ;
    }


    public function configureShowFields(ShowMapper $showMapper) {

        $container = $this->getConfigurationPool()->getContainer();
        $em = $container->get('doctrine.orm.entity_manager');

        $contact = $this->getSubject();
        $contact->setReaded(true);
        $em->persist($contact);
        $em->flush();

        $userEntity = $container->get('security.token_storage')->getToken()->getUser();

        $devisConfig = current($em
            ->getRepository(DevisConfig::class)
            ->findBy([
                'user_id' => $userEntity,
        ]));

        $sendDevis = (current($em
            ->getRepository(DevisEnvoye::class)
            ->findBy([
                'uuid' => $this->object->getUuid(),
            ])));


        // Generate URL of admin devis
        /** @var string $url */
        $url = $container->get('router')->generate('admin_app_devisenvoye_show', [
            'id' => $this->object->getUuid()
        ]);
        $url = substr($url,0,-4);

        // $this->object
        /*
        $sendDevis->setTva($devisConfig->getTva());
        $sendDevis->setAcompte($devisConfig->getAcompte());
        $sendDevis->setFranchise($devisConfig->getFranchise());
        $sendDevis->setValglobale($devisConfig->getValglobale());
        $sendDevis->setParobjet($devisConfig->getParobjet());
        $sendDevis->setValable($devisConfig->getValable());
        */


        $formEstimationPrix = $container->get('form.factory')->create(EstimationPrixForm::class, $sendDevis, [
            'action' => $container->get('router')->generate('sonata_sendDevis_post', [
                'uuid' => $this->object->getUuid(),
            ]),
        ])->createView();

        $showMapper
            ->tab($this->trans('Devis '.$sendDevis->getDevisNumber()), [
                'attr' => [
                    'icon' => '<i class="fas fa-mail-bulk"></i>'
                ]
            ])

            ->with('Estimation Prix', [
                'class'       => 'col-md-5',
                'attr' => [
                    'icon' => '<i class="fas fa-paper-plane"></i>',
                ]
            ])
            ->add('prixform', EstimationPrixForm::class, [
                "template" => "admin/demandedevis/estimation_prix.html.twig",
                'label' => 'Prix',
                'attr' => [
                    'form' => $formEstimationPrix,
                ]
            ])
            ->end()
            ->with('Devis '.$sendDevis->getDevisNumber(), [
                'class' => 'col-md-7',
                'attr' => [
                    'icon' => '<i class="fas fa-mail-bulk"></i>',
                ]
            ])
            ->add('preview', null, [
                'template' => 'admin/demandedevis/previsualisation_devis.html.twig',
                'mapped' => false,
                'attr' => [
                    'url_devis' => $url,
                ]
            ])
            ->end()
            ->with('DEVIS PRÉVISUALISER', [
                'class' => 'col-md-7',
                'attr' => [
                    'icon' => '<i class="fas fa-file-archive"></i>',
                ]
            ])
            ->add('listdocs', null, [
                'template' => 'admin/demandedevis/previsualisation_devis.html.twig',
                'mapped' => false,
            ])

            ->end()

            ->end()
            ->tab($this->trans('Devis Info'), [
                'attr' => [
                    'icon' => '<i class="fas fa-paperclip"></i>',
                ]
            ])
            ->with('General', [
                    'class'       => 'col-md-6',
                    'attr' => [
                        'icon' => '<i class="fas fa-clipboard-list"></i>',
                    ],
                ]
            )
            ->add('nom')
            ->add('prenom')
            ->add('telephone')
            ->add('email')

            ->end()
            ->with('Info Déménagement ',[
                'class'       => 'col-md-6 title_devis',
                'attr' => [
                    'icon' => '<i class="fas fa-info"></i>',
                ]
            ])
            ->add('CreatedDate', null, [
                'label' => 'Date de demande',
                'format' => 'd/m/Y',
            ])
            ->add('volume', null, [
                'label' => 'Volume',
            ])
            ->add('prestation', null, [
                'label' => 'Prestation'
            ])
            ->add('budget', TextType::class, [
                'label' => 'Budget',
                'mapped' => false,
            ])
            ->end()

            ->with('Info Depart' ,[
                'class'       => 'col-md-6',
                'attr' => [
                    'icon' => '<i class="fas fa-map-signs"></i>',
                ]
            ])
            ->add('date1')
            ->add('adresse1')
            ->add('cp1')
            ->add('ville1')
            ->add('etage1')
            ->add('ascenseur1')
            ->end()
            ->with('Info Arrivee' ,[
                'class'       => 'col-md-6',
                'attr' => [
                    'icon' => '<i class="fas fa-map-signs"></i>',
                ]
            ])
            ->add('date2')
            ->add('adresse2')
            ->add('cp2')
            ->add('ville2')
            ->add('etage2')
            ->add('ascenseur2',ChoiceType::class,[
                'attr' => [
                    'class' => 'asc_selector2',
                ],
            ])
            ->end()
            ->end()

        ;
    }

    protected function configureListFields(ListMapper $listMapper) {

        unset($this->listModes['mosaic']);

        $listMapper
            ->addIdentifier('devis_number', null, [
                'label' => 'Numero Devis',
                'route' => [
                    'name' => 'show',
                ]
            ])
            ->addIdentifier('prixht', null, [
                'label' => 'Prix HT ',
                'route' => [
                    'name' => 'show',
                ]
            ])

            ->addIdentifier('nom', null, [
                'route' => [
                    'name' => 'show',
                ]
            ])
            ->addIdentifier('prenom', null, [
                'route' => [
                    'name' => 'show',
                ]
            ])
              ->addIdentifier('email ', null, [
                  'route' => [
                      'name' => 'show',
                  ]
              ])
            ->addIdentifier('CreatedDate', null, array(
                'format' => 'd/m/Y',
                'label' => 'Devis Envoyée',
                'route' => [
                    'name' => 'show',
                ]
            ))

            // add custom action links
            ->add('_action', 'actions', [
                    'label'=> 'Action',
                    'actions' => array(
                        'show' => [
                            'template' => 'admin/action/show_action.html.twig'
                        ],
                        'edit' => [
                            'template' => 'admin/action/edit_action.html.twig'
                        ],
                        'delete' => [
                            'template' => 'admin/action/remove_action.html.twig'
                        ],
                    )]
            )
        ;
    }

}