<?php


namespace AppBundle\Admin;


use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Show\ShowMapper;
use Symfony\Component\DependencyInjection\Container;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class TelephoneAdmin extends AbstractAdmin
{

    /** @var object|string  */
    private $user;

    /** @var Container  */
    private $container;

    /**
     * PrestationCustomAdmin constructor.
     */
    public function __construct($code, $class, $baseControllerName, Container $container)
    {
        $this->container = $container;
        parent::__construct($code, $class, $baseControllerName);
    }

    /**
     * MesDevisAdmin constructor.
     * @param $object
     * @throws OptimisticLockException
     */
    public function preValidate($object) {

        $this->user = $this->container->get('security.token_storage')->getToken()->getUser();
        $object->setUserId($this->user);

        parent::preValidate($object); // TODO: Change the autogenerated stub
    }

    /**
     * @param $id
     * @return mixed|object|null
     */
    public function getObject($id)
    {
        $object = $this->getModelManager()->findOneBy($this->getClass(), [
            'uuid' => $id
        ]);
        $this->object = $object;
        return $object;
    }

    // We call new function for generating URL sonata
    /**
     * @param $entity
     * @return string
     */
    public function getUrlsafeIdentifier($entity)
    {
        return $this->getNormalizedIdentifier($entity);
    }

    // Here url make new paramters tu URL uuid
    /**
     * @param $entity
     * @return string
     */
    public function getNormalizedIdentifier($entity)
    {
        // If id not exist it wille be create
        if(is_null($entity->getId()))
        {
            return parent::getNormalizedIdentifier($entity);
        }
        // If id exist wie show url with UUID paramter
        else{
            return $entity->getUuid();
        }
    }

    /**
     * @param string $context
     * @return \Sonata\AdminBundle\Datagrid\ProxyQueryInterface
     */
    public function createQuery($context = 'list')
    {

        // Get connected user
        $userEntity = $this->container->get('security.token_storage')->getToken()->getUser();
        // Check if user have owner parent
        if(!is_null($userEntity->getParent())) {
            $userEntity = $userEntity->getParent();
        }

        $query = parent::createQuery($context);
        $alias = $query->getRootAliases()[0];

        // Filtering for only owner user
        $query
            ->where($alias.'.user_id = :user_id')
            ->setParameters([
                'user_id' => $userEntity->getId(),
            ])
        ;

        return $query;
    }

    /**
     * @param FormMapper $formMapper
     */
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->add('type', ChoiceType::class, [
                'label' => $this->trans('type.telephone'),
                'choices'  => [
                    'Téléphone Fix' => 'telephone.fix',
                    'Portable' => 'portable',
                    'Fax' => 'fax',
                ],
                'attr' => [
                    'class' => 'form-control',
                    'divclass' => 'col-md-4'
                ],
            ])
            ->add('numero', TextType::class, [
                'label' => $this->trans('numero.tel')
            ])
            ;
    }

    /**
     * @param ListMapper $list
     */
    protected function configureListFields(ListMapper $list)
    {
        unset($this->listModes['mosaic']);

        $list
            ->addIdentifier('numero', null, [
                'label' => $this->trans('numero.tel'),
                'route' => [
                    'name' => 'show',
                ]
            ])
            ->addIdentifier('type', null, [
                'label' => $this->trans('type.telephone'),
                'route' => [
                    'name' => 'show',
                ]
            ])
        ;
    }

    /**
     * @param ShowMapper $show
     */
    protected function configureShowFields(ShowMapper $show)
    {
        $show
            ->add('numero', TextType::class, [
                'label' => $this->trans('numero.tel'),
            ])
            ->add('type', TextType::class, [
                'label' => $this->trans('type.telephone'),
            ])
            ;
    }

}