<?php
/**
 * Created by PhpStorm.
 * User: rpetrosjan
 * Date: 25/03/2019
 * Time: 02:24
 */

namespace AppBundle\Admin;


use AppBundle\Entity\UserConnect;
use Doctrine\ORM\EntityManagerInterface;
use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\ListMapper;

/**
 * Class UserConnectAdmin
 * @package AppBundle\Admin
 */
class UserConnectAdmin extends AbstractAdmin
{

    private $em;

    /**
     * @param string $code
     * @param string $class
     * @param string $baseControllerName
     * @param EntityManagerInterface $em
     */
    public function __construct($code, $class, $baseControllerName, EntityManagerInterface  $em)
    {
        parent::__construct($code, $class, $baseControllerName);
        $this->em = $em;
    }

    // Creating Sort By DateTime ASC
    /**
     * @var array
     */
    protected $datagridValues = [
        '_page' => 1,
        '_sort_order' => 'DESC',
        '_sort_by' => 'CreatedDate',
    ];


    /**
     * @return array|mixed
     */
    public function getDashboardActions()
    {
        /** @var User $user */
        $user = $this->getConfigurationPool()->getContainer()->get('security.token_storage')->getToken()->getUser();

        /** @var array $result */
        $resultArray = $this->em->getRepository(UserConnect::class)->getLastConnectList(5, $user);

        //Preparing data for a Table

        $tbody = [];
        foreach ($resultArray as $result) {
            $tbody[] = [
                'Date' => $result->getCreatedDate()->format('d/m/Y H:s'),
                'IP' => $result->getIp()
            ];
        }

        $actions['pageDashboard'][] = [
            'table' => [
                'thead' => [
                    [
                        'name'=>'Date'
                    ],
                    [
                        'name'=> 'IP'
                    ],
                ],
                'tbody' => $tbody
            ],
            'template' => 'admin/dashboard/table.html.twig',
        ];
        return $actions;
    }

    public function configureListFields(ListMapper $list)
    {
        $list
            ->add('CreatedDate')
            ->add('ip')
        ;
        parent::configureListFields($list); // TODO: Change the autogenerated stub
    }
}